import { ProviderHealthScorer, ScoredRateProvider, FxProviderRouter, sanitiseProviderId } from './providerHealthScorer';
import { MetricsCollector } from '../lib/metrics';
import { Logger } from '../lib/logger';

test('all requirements', async () => {
  const metrics = new MetricsCollector({ enabled: true });
  const logger = new Logger();
  const s = new ProviderHealthScorer({ windowSize: 10, minCallsForEvaluation: 5, demotionSuccessRate: 0.8, promotionSuccessRate: 0.9, demotionLatencyP95Ms: 500, promotionLatencyP95Ms: 200, demotionRateAgeMs: 10000, promotionRateAgeMs: 5000, recoveryWindowMs: 0 }, metrics, logger);
  expect(() => new ProviderHealthScorer({ demotionSuccessRate: 0.9, promotionSuccessRate: 0.9 }, metrics, logger)).toThrow();
  for (let i=0;i<4;i++) s.record('p1', { success: false });
  expect(s.isHealthy('p1')).toBe(true);
  s.record('p1', { success: false });
  expect(s.isHealthy('p1')).toBe(false);
  const s2 = new ProviderHealthScorer({ windowSize: 10, minCallsForEvaluation: 10, demotionSuccessRate: 0.8, promotionSuccessRate: 0.9, demotionLatencyP95Ms: 500, promotionLatencyP95Ms: 200, demotionRateAgeMs: 10000, promotionRateAgeMs: 5000, recoveryWindowMs: 0 }, metrics, logger);
  for (let i=0;i<8;i++) s2.record('p2', { success: true });
  for (let i=0;i<2;i++) s2.record('p2', { success: false });
  expect(s2.isHealthy('p2')).toBe(true);
  for (let i=0;i<10;i++) s.record('p3', { success: true, latencyMs: 600 });
  expect(s.isHealthy('p3')).toBe(false);
  for (let i=0;i<10;i++) s.record('p4', { success: true, rateAgeMs: 20000 });
  expect(s.isHealthy('p4')).toBe(false);
  for (let i=0;i<5;i++) s.record('p5', { success: false });
  expect(s.isHealthy('p5')).toBe(false);
  expect(sanitiseProviderId('p/1:2')).toBe('p_1_2');
  const p = { id: 'p1', getRate: async () => 1.1 };
  const r = new FxProviderRouter([p], s as any);
  expect(await r.getRate('USD','EUR')).toBe(1.1);
  const sp = new ScoredRateProvider(s, 'p1', p as any);
  expect(await sp.getRate('USD','EUR')).toBe(1.1);
});