import 'dotenv/config';
import express from 'express';
import cors from 'cors';
import morgan from 'morgan';
import { pool } from './db/pool';
import { createRequireAuth } from './middleware/auth';
import { createCorsMiddleware } from './middleware/cors';
import { SessionRepository } from './db/repositories/sessionRepository';
import { WebhookEndpointRepository } from './db/repositories/webhookEndpointRepository';
import { createAdminWebhooksRouter } from './routes/adminWebhooks';
import { createLogoutRouter } from './auth/logout/logoutRoute';
import { createChangePasswordRouter } from './auth/changePassword/changePasswordRoute';
import { createLoginRouter } from './auth/login/loginRoute';
import { createHealthRouter } from './routes/health';
import { dbHealth } from './db/client';
import { createOfferingSyncRouter } from './routes/offeringSync';
import { UserRepository } from './db/repositories/userRepository';
import { JwtIssuer, UserRole, UserRepository as IUserRepository, SessionRepository as ISessionRepository } from './auth/login/types';
import { LoginService } from './auth/login/loginService';
import { issueToken } from './lib/juwt';
import { MetricsCollector } from './lib/metrics';
import { metricsMiddleware, createPrometheusHandler } from './middleware/metricsMiddleware';
import { Logger } from './lib/logger';
import { RefreshService } from './auth/refresh/refreshService';
import { createRefreshRouter } from './auth/refresh/refreshRoute';
import { RefreshTokenRepository, TokenService } from './auth/refresh/types';
import { RefreshTokenRepositoryAdapter } from './auth/refresh/repositoryAdapter';
import { JwtTokenServiceAdapter } from './auth/refresh/tokenServiceAdapter';
import { errorHandler } from './middleware/errorHandler';
import { SocialIdentityRepository } from './db/repositories/socialIdentityRepository';
import { SocialUserRepositoryAdapter } from './auth/social/socialUserRepositoryAdapter';
import { SocialAuthService } from './auth/social/socialAuthService';
import { createDefaultSocialTokenVerifierFromEnv } from './auth/social/providerVerifiers';
import { createSocialAuthRouter } from './auth/social/socialAuthRoute';
import { createReconciliationMetricsHandler } from './routes/reconciliationRoutes';
